### ISSUE TITLE
[BUG] Packagist não irá atualizar repositório sozinho.

### ISSUE THREAD

**Issue by guifabrin** [fauxcompany/escreve_numero#5]
![image](https://user-images.githubusercontent.com/30579757/56208176-dcbe6600-6026-11e9-943f-127a7df7f2a7.png)

**Comment by leomoty** [comment]
Esqueci de responder sobre essa issue, aparentemente, você tem de setar o webhook, eu não tenho permissão no packagist :)

**Comment by guifabrin** [comment]
@leomoty Te coloquei como maintainers, verifica se você consegue acessar.

**Comment by guifabrin** [comment]
@leomoty, agora que você lançou a pre release já temos isso?

**Comment by leomoty** [comment]
@guifabrin está resolvido, era o webhook pro repo. Esqueci da issue.
