### ISSUE TITLE
[NEW] Incluir mais testes

### ISSUE THREAD

**Issue by leomoty** [fauxcompany/escreve_numero#9]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**

Só estamos testando um caso que a biblioteca dá suporte.

**Descreva a solução que você gostaria**

Incluir pelo menos um teste para cada tipo de resultado que aceitamos. Idealmente testando algum caso errado, por exemplo, o que acontece se o input for `e`?

**Comment by leomoty** [comment]
Além disso:

* dava pra testar se estourou o limite superior...
* Aceita número negativo...

Se eu lembrar vou adicionando mais.

**Comment by guifabrin** [comment]
@leomoty e de euler ou e de letra e?

**Comment by leomoty** [comment]
@guifabrin tanto faz, estava pensando num input inválido mesmo.

**Comment by leomoty** [comment]
Parcialmente o #12 resolve já, só queria algum case que o input não pode ser convertido.
